applications:
- name: atk-broker
  env:
    CF_API: http://api.<run_domain>
    CF_USER: <admin_username>
    CF_PASS: <user_password>
- name: hdfs-broker
  env:
    USER_PASSWORD: <hdfs_user_pass>
    KRB_KDC_HOST: <kerberos_host>
    KRB_REALM: <kerberos_realm>
    BROKER_PATH: <broker_folder_on_hdfs>
    HADOOP_PROVIDED_PARAMS: <import_hadoop_conf>
    SPRING_PROFILES_ACTIVE: cloud,secure
- name: kafka-broker
  memory: 128M
  env:
    CREDENTIALS: '{"uri": "<kafka_ip_1>:9092,<kafka_ip_2>:9092,<kafka_ip_3>:9092"}'
- name: app-launcher-helper
  env:
    API_URL: http://api.<run_domain>
    TOKEN_KEY_URL: http://uaa.<run_domain>/token_key
- name: cdh-broker
  memory: 128M
  env:
    CREDENTIALS: '{"hdfs_root": "hdfs://<namenode_internal_host>:8020/user/iauser", "zk_host": "<zookeeper_ip>", "zk_port": "2181", "spark_max_memory": "2163212288", "resource_manager" : "http://<namenode_internal_host>:8088", "yarn_config": "http://<cloudera_manager_internal_host>:7180/api/v9/clusters/<CDH_cluster_name>/services/YARN/clientConfig", "hdfs_config": "http://<cloudera_manager_internal_host>:7180/api/v9/clusters/<CDH_cluster_name>/services/HDFS/clientConfig", "hbase_config": "http://<cloudera_manager_internal_host>:7180/api/v9/clusters/<CDH_cluster_name>/services/HBASE/clientConfig"}'
- name: zookeeper-wssb-broker
  memory: 128M
  env:
    CREDENTIALS: '{"uri": "<zookeeper_ip_1>:2181,<zookeeper_ip_2>:2181,<zookeeper_ip_3>:2181"}'
- name: smtp-broker
  memory: 128M
  env:
    CREDENTIALS: '{"port_ssl": "465", "username": "<user>", "password": "<pass>", "port": "25", "hostname": "email-smtp.us-west-2.amazonaws.com"}'
- name: gearpump-broker
  env:
    USER_PASSWORD: <gearpump_user_pass>
    KRB_KDC_HOST: <kerberos_host>
    KRB_REALM: <kerberos_realm>
    GEARPUMP_URI: http://<gearpump_webui_server_host>:8090
    gearpumpBRK_SPACE: <gearpump_broker_znode_in_zookeeper>
- name: hbase-broker
  env:
    USER_PASSWORD: <hbase_user_pass>
    KRB_KDC_HOST: <kerberos_host>
    KRB_REALM: <kerberos_realm>
    ZK_BRK_SPACE: <hbase_broker_znode_in_zookeeper>
- name: zookeeper-broker
  env:
    USER_PASSWORD: <zookeeper_user_pass>
    KRB_KDC_HOST: <kerberos_host>
    KRB_REALM: <kerberos_realm>
    ZK_CLUSTER_URL: <zookeeper_ip_1>:2181,<zookeeper_ip_2>:2181,<zookeeper_ip_3>:2181
    ZK_BRK_ROOT: <zookeeper_broker_metadata>
    ZK_BRK_SPACE: <zookeeper_broker_userspace>
- name: yarn-broker
  env:
    USER_PASSWORD: <yarn_user_pass>
    KRB_KDC_HOST: <kerberos_host>
    KRB_REALM: <kerberos_realm>
    HADOOP_PROVIDED_PARAMS: <import_hadoop_conf>
    YARNBRK_SPACE: <yarn_broker_znode_in_zookeeper>
user_provided_service_instances:
- name: sso
  credentials:
    apiEndpoint: http://api.<run_domain>
    authorizationUri: http://login.<run_domain>/oauth/authorize
    checkTokenUri: http://uaa.<run_domain>/check_token
    clientId: developer_console
    clientSecret: <developer_console_password>
    logoutUri: http://login.<run_domain>/logout.do
    tokenKey: http://uaa.<run_domain>/token_key
    tokenUri: http://uaa.<run_domain>/oauth/token
    uaaUri: http://uaa.<run_domain>
    userInfoUri: http://uaa.<run_domain>/userinfo
    email: <email_addres>
- name: nats-provider
  credentials:
    url: nats://<nats_username>:<password>@<nats_ip>:4222
    service-creation-subject: <topic-name>
- name: gorouter-provider
  credentials:
    username: <router_username>
    password: <password>
- name: datacatalog
  credentials:
    host: http://data-catalog.<apps_domain>
- name: servicecatalog
  credentials:
    host: http://service-catalog.<apps_domain>
- name: dataaquisitionservice
  credentials:
    host: http://das.<apps_domain>
- name: metrics-provider
  credentials:
    host: http://metrics-provider.<apps_domain>
- name: app-launcher-helper
  credentials:
    host: http://app-launcher-helper.<apps_domain>
- name: user-management
  credentials:
    host: http://user-management.<apps_domain>
- name: hue
  credentials:
    hueUrl: http://hue.<domain>/metastore/table
- name: arcadia
  credentials:
    arcadiaUrl: http://arcadia.<domain>/arc/apps/data
- name: datacatalogexport
  credentials:
    host: http://hive.<apps_domain>
- name: hive
  credentials:
    # for systems without Arcadia
    hiveUrl: jdbc:hive2://<namenode_internal_host>:10000/
    # for systems with Arcadia
    # hiveUrl: jdbc:hive2://<any_arcadia_node>:31050/auth=noSasl
    hiveUser: hdfs
- name: platformcontext
  credentials:
    host: http://platform-context.<apps_domain>
- name: fileserver
  credentials:
    host: http://file-server.<apps_domain>
- name: router-metrics-provider
  credentials:
    host: http://router-metrics-provider.<apps_domain>
- name: metadataparser
  credentials:
    url: http://metadata.<apps_domain>
- name: downloader
  credentials:
    url: http://hdfs-downloader.<apps_domain>
service_brokers:
- name: docker
  broker_url: http://cf-containers-broker.<run_domain>
  auth_username: <user>
  auth_password: <pass>
- name: hdfs
  broker_url: https://hdfs-broker.<apps_domain>
  auth_username: <user>
  auth_password: <hdfs_user_pass>
- name: zookeeper-wssb
  broker_url: http://zookeeper-wssb-broker.<apps_domain>
  auth_username: <user>
  auth_password: <pass>
- name: kafka
  broker_url: http://kafka-broker.<apps_domain>
  auth_username: <user>
  auth_password: <pass>
- name: atk
  broker_url: http://atk-broker.<apps_domain>
  auth_username: <user>
  auth_password: <pass>
- name: cdh
  broker_url: http://cdh-broker.<apps_domain>
  auth_username: <user>
  auth_password: <pass>
- name: smtp
  broker_url: http://smtp-broker.<apps_domain>
  auth_username: <user>
  auth_password: <pass>
- name: gearpump
  broker_url: http://gearpump-broker.<apps_domain>
  auth_username: <user>
  auth_password: <gearpump_user_pass>
- name: hbase
  broker_url: http://hbase-broker.<apps_domain>
  auth_username: <user>
  auth_password: <hbase_user_pass>
- name: zookeeper
  broker_url: http://zookeeper-broker.<apps_domain>
  auth_username: <user>
  auth_password: <zookeeper_user_pass>
- name: yarn
  broker_url: http://yarn-broker.<apps_domain>
  auth_username: <user>
  auth_password: <yarn_user_pass>
